theme: minima

title: Reinhard's playground
author: Reinhard Lackner
email: blog@nerei.net
url: https://nerei.net

timezone: UTC # GitHub uses UTC. This is to force dev environment to match
future: false # GitHub Pages will publish future posts if this isn't set to false

description: >-
  "I can't change the direction of the wind, but I can adjust my sails to always reach my destination." -- Jimmy Dean

show_excerpts: false

# Used by simple links page
minima:
  social-links:
    website: https://nerei.net
    mastodon: macf00bar, https://hachyderm.io/@macf00bar
    github:   macf00bar, https://github.com/mAcf00bar

# plugin: jekyll-titles-from-headings
titles_from_headings:
  strip_title: true

header_pages:
  #- resume.html
  - archive.html
  - bookmarks.md

plugins:
  - jekyll-feed
  - jekyll-sitemap

gravatar_hash: cd578fbc364f6c950ffc3585570b0f7f
code_block_max_height: 500px

home_post_limit: 5

defaults:
  - scope:
      path: ""
    values:
      image: https://s.gravatar.com/avatar/cd578fbc364f6c950ffc3585570b0f7f?s=80 # Apply default site image
  - scope:
      path: ""
      type: posts
    values:
      tags:
        - Other # Add a default tag to all posts

# Disable highlighting to use highlightJS instead
# highlighter: none # Not supported by GitHub Pages
kramdown:
  syntax_highlighter_opts:
    disable: true

include: [".well-known"]
